name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:  # 手动触发
  push:              # 代码推送触发
    branches:
      - master        # 监听 main 分支的推送
  # 如果你想触发对某些特定目录或文件的更改，也可以使用 paths 配置：
  # paths:
  #   - 'src/**'
  #   - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6.1


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Bump version
        uses: phips28/gh-action-bump-version@v10
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
